# Generated by Django 3.0.8 on 2020-07-27 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usregister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=40)),
                ('paswd', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
