# Generated by Django 3.0.8 on 2020-07-27 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usregister',
            old_name='paswd',
            new_name='pwd',
        ),
    ]
