# Generated by Django 3.0.8 on 2020-07-29 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200727_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usregister',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
